version: "3.8"
services:
  mongo:
    image: mongo:6.0.4
    container_name: zorak_mongo
    volumes:
      - ./db:/data/db
    user: "1001"
    restart: always

  zorak:
    build: .
    image: zorak:${TAG}
    container_name: zorak_bot
    env_file: .env
    links:
      - "mongo:mongo"
    depends_on:
      - mongo
    user: "1001"
    restart: always
