name: Deploy to EC2

on:
  push:
    branches:
      - Main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_KEY }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'ENDSSH'
            cd /srv/ZorakBot
            sudo git pull
            docker-compose up -d --build zorak_bot_prod
          ENDSSH
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}